### ISSUE TITLE
Problem with more than one level nesting

### ISSUE THREAD

**Issue by danielcaballero** [scala-tsi/scala-tsi#126]
Tested on version 0.4.1

For case classes with one level of nesting it works as expected:

Input:
```scala
case class Bug(
  prop1: String,
  prop2: Nest1
)

case class Nest1(
  prop3: String,
  prop4: Int
)
```
Result:
```typescript
export interface IBug {
  prop1: string
  prop2: INest1
}

export interface INest1 {
  prop3: string
  prop4: number
}
```

However for 2 or more levels of nesting like:
```scala
case class Bug(
  prop1: String,
  prop2: Nest1
)

case class Nest1(
  prop3: String,
  prop4: Nest2
)

case class Nest2(
  prop5: String,
  prop6: Int
)
```

I am getting the error: 

```none
[error] ./target/scala-2.12/src_managed/com/scalatsi/generator/ExportTypescript.scala:18:43: 
[error] Circular reference encountered while searching for TSType[String]
[error] Please break the cycle by locally defining an implicit TSType like so:
[error] implicit val tsType...: TSType[...] = {
[error]   implicit val tsA: TSType[String] = TSType.external("IString") // name of your "String" typescript type here
[error]   TSType.getOrGenerate[...]
[error] }
[error] for more help see https://github.com/scala-tsi/scala-tsi#circular-references
[error]       """Bug""" -> ts.TSType.getOrGenerate[Bug].get, 
[error]                                           ^
[error] one error found
```

There is no circular reference here so I believe this behaviour is not correct.

Also note that in the message ```Circular reference encountered while searching for TSType[A]``` type `A` will be the type of the first property of `Nest2`

**Comment by dhoepelman** [comment]
So the problem is that I never got circular reference detection to work inside the auto- generating macros. Instead I measure how deep we are and stop it at a certain point.

That's supposed to be 7+ levels deep, not 2. I'll look into it.

In the meantime, you can work around it by explicitly using the macro in the correct order, until the nesting is shallow enough to not trigger the bug.

```
object MyTSTypes {
  implicit val nest2ts = TSType.fromCaseclass[Nest2]
  implicit val nest1ts = TSType.fromCaseclass[Nest1]
  // "Bug" should not be necessary
}
```
