### ISSUE TITLE
Generation for `Null` type fails without alias

### ISSUE THREAD

**Issue by jnatten** [scala-tsi/scala-tsi#172]
I am trying to use `scala-tsi` to generate some typescript types for my frontend to use.
One of the types we have for one of our apis is:
```scala
case class ParentType(
  someOther: Either[Null, Option[SomeOtherType]]
)
```

I would expect this to generate to `ISomeOtherType | null | undefined` but instead it fails with:
```
[error] (...)/ExportTypescript.scala:23:54: kinds of the type arguments (scala.util.Left) do not conform to the expected kinds of the type parameters (type T).
[error] scala.util.Left's type parameters do not match type T's expected parameters:
[error] class Left has 2 type parameters, but type T has 0
[error]       """ParentType""" -> ts.TSType.getOrGenerate[ParentType].get,
[error]                                                      ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

I have been able to work around it by defining an alias for `Null`, but it seems unnecessary:
```scala
implicit val _ = TSType.alias[Null]("NullAlias", TSNull)
```

Feel free to close if intended :smile:

**Comment by dhoepelman** [comment]
This is a relatively simple oversight, since `Null` type is rare in Scala.

Adding the following in your scope should work:
```
implicit val nullTsType: TSType[Null] = TSType(TSNull)
```

Feel free to add a PR to add the following to `PrimitiveTSTypes ` + a test.
