### ISSUE TITLE
Allow to delete fields from TSNamedType 

### ISSUE THREAD

**Issue by heaven-born** [scala-tsi/scala-tsi#287]
Deleting fields is supported only for `TSIType`. It is useful to also add this support for `TSNamedType`. In this case, it would mean "delete if exists".  In my specific case, scala-tsi generates a 'type' field for each element in the sealed family, but I don't want this field to appear in TS classes.

**Comment by dhoepelman** [comment]
If you do not want the `type` field for tagged unions/sealed family, you can set [the configuration option](https://github.com/scala-tsi/scala-tsi#configuration) `typescriptTaggedUnionDiscriminator` to `None`.

The specific request is not feasible, because more than just interfaces are `TSNamedType`, e.g. what would removing a field from `type X = string` even mean?

**Comment by heaven-born** [comment]
The original plan was to remove the Discriminator, but I misunderstood the documentation and attempted to do it individually for each element of the sealed family one by one. I apologize. Since the initial plan can be done using `typescriptTaggedUnionDiscriminator`, I will close the ticket.

**Comment by heaven-born** [comment]
Actually, there is still one issue. One set of my sealed family needs the discriminator and the other one doesn't. Using  `typescriptTaggedUnionDiscriminator` I can disable it for the whole generation process only, so now I have to keep this field in my TS classes and create multiple `TSType` implicit for each element for the family where I want to exclude it. Is it possible to introduce the enum level granularity for this configuration?

**Comment by dhoepelman** [comment]
If it's only for one or a small number of your types, I would add it to the implicits of those specific types and set `typescriptTaggedUnionDiscriminator` to none.

i.e.
```scala
case class Subclass(...) extend SealedFamily
object Subclass {
  import com.scalatsi.dsl.*
  implicit val subclassTsType: TSIType[Subclass] = TSType.fromCaseClass[Subclass] + ("type" -> "Subclass")
}
```

this will be picked up by the part that generates `SealedFamily`

If you want it for most but not all, you can do the same but instead remove it for the few types you don't want

**Comment by dhoepelman** [comment]
I would accept a PR that makes this behavior more configurable (e.g. sealed hierarchy level) and/or introduces a naming strategy, but I have no interest in doing it myself currently.
