### ISSUE TITLE
Converting Optional types

### ISSUE THREAD

**Issue by psyanite** [scala-tsi/scala-tsi#362]
```
case class Person(
  age: Option[Int],
)
```

is converted to

```
export interface IPerson {
  age?: number
}
```

But technically shouldn't it be the following:
```
export interface IPerson {
  age: number | null
}
```

**Comment by dhoepelman** [comment]
That depends a lot on the case and your local setup. In general there's isn't a nice match between Javascripts 2 "null" types (null and undefined) and Scala's None. Sometimes you want one, other times the other, and 90% of the time the difference doesn't matter.

E.g. when an API returns `{ "age": null }` or `{}` for None is not universally the same. Same whether `{}` and/or `{ "age": null` }` are accepted.

You can control the behavior by overriding the TSType locally, or providing your own implicit def closer to the default one.

```scala
// By default scala-tsi uses undefined, we want null
implicit def tsOptionWithNull[E](implicit e: TSType[E]): TSType[Option[E]] = TSType(e | TSNull)
```

**Comment by psyanite** [comment]
Oh awesome! I'll try that out. Thanks for the fast reply!!!
